// Code generated by goctl. DO NOT EDIT.
package types

type InfoReq struct {
	ID uint `json:"id"`
}

type InfoResp struct {
	ID            uint   `json:"id"`
	UserName      string `json:"username"`
	Telephone     string `json:"telephone"`
	Name          string `json:"name"`
	Gender        string `json:"gender"`
	Email         string `json:"email"`
	Photo         string `json:"photo"`
	Website       string `json:"website"`
	Bio           string `json:"bio"`
	Birthday      string `json:"birthday"`
	WatchsCounts  uint   `json:"watchs_counts"`
	FansCounts    uint   `json:"fans_counts"`
	CommentsCount uint   `json:"comments_count"`
	PostsCounts   uint   `json:"posts_counts"`
}

type UserDto struct {
	ID           uint   `json:"id"`
	UserName     string `json:"username"`
	Name         string `json:"name"`
	Photo        string `json:"photo"`
	Website      string `json:"website"`
	Bio          string `json:"bio"`
	WatchsCounts uint   `json:"watchs_counts"`
	FansCounts   uint   `json:"fans_counts"`
	PostsCounts  uint   `json:"posts_counts"`
	IsWatched    bool   `json:"is_watched"`
}

type EditInfoReq struct {
	UserName    string `json:"user_name" example:"zzk"`
	Name        string `json:"name" example:"志明"`
	PhotoBase64 string `json:"photo_base64"`
	Photourl    string `json:"photourl"`
	Website     string `json:"website" example:"https://example.com"`
	Bio         string `json:"bio" example:"my bio"`
	Gender      string `json:"gender" example:"mele"`
	Birthday    string `json:"birthday" example:"2022-12-12"`
}

type EditInfoResp struct {
	Status     bool  `json:"status"`
	UpdataTime int64 `json:"updata_time"`
}

type AttemptReq struct {
	Username     string `json:"username" binding:"required" example:"zzk"`
	Name         string `json:"name" binding:"required" example:"志明"`
	Password     string `json:"password" binding:"required" example:"123456"`
	EmailOrPhone string `json:"emailorphone" binding:"required" example:"1652091948@qq.com"`
}

type AttemptResp struct {
	Ok     bool   `json:"ok"`
	Reason string `json:"reason"`
}

type RegisterReq struct {
	Username     string `json:"username" binding:"required" example:"zzk"`
	Name         string `json:"name" binding:"required" example:"志明"`
	Password     string `json:"password" binding:"required" example:"123456"`
	EmailOrPhone string `json:"emailorphone" binding:"required" example:"1652091948@qq.com"`
	Telephone    string `json:"telephone" swaggerignore:"true" example:""`
	Email        string `json:"email" swaggerignore:"true" example:""`
	Birthday     string `json:"birthday" example:"2022-12-12"`
	Code         string `json:"code" example:"1234"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	EmailOrPhoneOrUsername string `json:"emailorphoneorusername" binding:"required" example:"zzk"`
	Password               string `json:"password" binding:"required" example:"123456"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
